
COMP=javac -cp .:/home/rubimonti/algs4.jar

clean:
	rm *.class

rational:
	$(COMP) Rational.java

rationalc:
    $(COMP) RationalClient.java

linear:
	$(COMP) LinearSearchCounter.java

slinear:
	$(COMP) SortedLinearSearchCounter.java

binary:
	$(COMP) SortedBinarySearchCounter.java

rectangulos:
	$(COMP) ClienteInterval2D.java

ej2: rationalc rational

ej3: linear slinear binary